topics:
- name    : joy
  topic   : remote_joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 8
- name    : navigation_func #external
  topic   : /nav_vel # cmd_vel
  timeout : 0.5
  priority: 1
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255
