#<!-- Frame names -->
scan: "scan"
base_frame: "base_link"
map_frame: "map"
odom_frame: "odom"
# -------------------
map_update_interval: 1.0
maxUrange: 100.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 0.3
angularUpdate: 0.15
temporalUpdate: 2.0
resampleThreshold: 0.5
particles: 50
# <!-- Map size -->
xmin: -200.0
ymin: -200.0
xmax: 200.0
ymax: 200.0
# -----------------
delta: 0.1
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
# use_sim_time: "true"
