#Configuation for robot odometry EKF
#
frequency: 50
publish_tf: true
odom0: jackal_velocity_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, true,
               false, false, true,
               false, false, false]
odom0_differential: false

# imu0: imu/data
# imu0_config: [false, false, false,
#               true, true, true,
#               false, false, false,
#               true, true, true,
#               false, false, false]
# imu0_differential: false

world_frame: odom
odom_frame: odom
base_link_frame: base_link

predict_to_current_time: true

initial_state: [0.0,  0.0,  0.0,
                0.0,  0.0,  0.0,
                0.0,  0.0,  0.0,
                0.0,  0.0,  0.0,
                0.0,  0.0,  0.0]
