topics:
- name    : keyboard
  topic   : teleop_keyboard/cmd_vel
  timeout : 0.5
  priority: 10
- name    : joy
  topic   : teleop_joy/cmd_vel
  timeout : 0.5
  priority: 9
- name    : vr
  topic   : teleop_vr/cmd_vel
  timeout : 0.5
  priority: 8
- name    : autonomous
  topic   : nav_vel
  timeout : 0.5
  priority: 1
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255
